// <auto-generated />
namespace Payroll_Sys.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addingfieldstotable1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addingfieldstotable1));
        
        string IMigrationMetadata.Id
        {
            get { return "202111171745382_Adding fields to table -1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
