// <auto-generated />
namespace Payroll_Sys.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Keyinregisterviewmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Keyinregisterviewmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202111192033443_Key in registerviewmodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
